POST http://zeraspeth:8081/users/logout
Content-Type: application/json
Authorization:jwt eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVkZDU3OWE3YTEyY2VmNjU5NGEwZTEyMCIsImVtYWlsIjoiYm9zc0BmcmVlLmZyIiwiaWF0IjoxNTc0NTAyMTkxLCJleHAiOjE1NzQ1MDM5OTF9.hqXc63lku05NrGSWMkk-fp3UdIltJ2bZE5UC9bNEJsU
