GET http://zerasp:8081/users/mylog
Content-Type: application/json
authorization: jwt eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVkZDU3OTBkN2IwNTc3NWIwMGM2NjY3NyIsImVtYWlsIjoieXZlc0BmcmVlLmZyIiwiaWF0IjoxNTc2NTk1MjAzLCJleHAiOjE1NzY1OTUzMjN9.1cm0nH77FZWLxd4GLeq-yculdrPpjZXV-Jcq0rNBqx8

{
  "severity": [ "3", "1" ],
  "lineslimit": 10
}