GET http://vboxnode:8081/users/listrequested?attrlist=email name _id&filter=yves@free.fr
Content-Type: application/json
Authorization: jwt eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlMWVlMDc4ZWU5YmVjMzI2NGQzYmU2MyIsImVtYWlsIjoieXZlc0BmcmVlLmZyIiwiaWF0IjoxNTc5MjU2Njk4LCJleHAiOjE1NzkyNTcyOTh9.7Coapw3wARpqPst4JllyPQU-nT7S4LkvTGuzBXPpGkk


